#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
          ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
          mv "$dir/$$.tags" "$dir/tags"

# Haskell!
if hash fast-tags > /dev/null 2>&1; then
    git ls-files '*.hs' | xargs fast-tags -o .hs-tags
fi
