#!/bin/sh

lint() {
    fileregex="$1"
    binary="$2"
    files=$(git diff --name-only --diff-filter=ACMRTUXB --cached -- "$fileregex")

    filtered=""
    for f in $files; do
        # Always skip zsh scripts, since these cannot be linted with shellcheck
        if ! head -1  "$f" | grep -q zsh 2>/dev/null; then
            filtered="$filtered $f"
        fi
    done

    if [ -z "$filtered" ]; then
        return
    fi

    if ! hash "$binary" 2>/dev/null; then
        echo "Warning: no $binary binary in PATH."
        return
    fi

    lint=$(echo "$filtered" | xargs "$binary")
    if [ "$?" -ne "0" ]; then
        echo "$binary linting errors:"
        echo "$lint"
        exit 1
    fi
}

lint "*.hs"  "hlint"
#lint "*.nix" "nixpkgs-fmt"
lint "*.py"  "pyflakes"
lint "*.sh"  "shellcheck"
