name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: 'echo Hello world, this is a placeholder'
